# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Personal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Personal
  pod 'RxSwift','>= 5.0.0'
  pod 'RxCocoa','>= 5.0.0'

end
